name: Sync Fork

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: HelloWRC
          repo: ClassIsland
          head: master
          base: master
          retries: 2
          retry_after: 5
          auto_approve: true
          auto_merge: true
          pr_title: "[Master] Fork Sync"

      - uses: tgymnich/fork-sync@v1.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: HelloWRC
          repo: ClassIsland
          head: dev
          base: dev
          retries: 2
          retry_after: 5
          auto_approve: true
          auto_merge: true
          pr_title: "[Dev] Fork Sync"

      - name: Echo Error
        if: ${{ failure() }}
        run: |
          echo "Fail to sync fork.May be there is no differences between the parent repository and this fork."
          exit 0

      - name: Echo Success
        if: ${{ !failure() }}
        run: |
          echo "Success to sync fork."
          exit 0
